spring:
#  profiles:
#    active: local
  application:
    name: analysis-dispatcher
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Phnom_Penh
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

custom:
  rest-client:
    enabled: true
    logging:
      enabled: true
    clients:
      default-connector:
        connect-timeout: 2000ms
        read-timeout: 5000ms
        connection-request-timeout: 2000ms
        ssl-enabled: false
        connection-pool:
          max-total: 200
          max-per-route: 100
          ttl: 300000ms
          validate-after-inactivity: 2000ms
          evict-idle-connections: 30000ms

telegram:
  bot:
    enabled: ${bot_enabled}
    token: ${bot_token}
    username: ${bot_username}
    chat-id: ${chat_id}
    app-webhook-url: ${app_webhook_url}

    telegram-url: https://api.telegram.org/bot
    delete-webhook: /deleteWebhook
    update-webhook: /getUpdates
    send-message: /sendMessage
    set-webhook: /setWebhook?url=

public-url:
  xau-price: https://api.gold-api.com/price/XAU
  forex-factory: https://nfs.faireconomy.media/ff_calendar_thisweek.json