spring:
  application:
    name: analysis-dispatcher
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Phnom_Penh
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

custom:
  rest-client:
    enabled: true
    logging:
      enabled: true
    clients:
      default-connector:
        connect-timeout: 2000ms
        read-timeout: 5000ms
        connection-request-timeout: 2000ms
        ssl-enabled: false
        connection-pool:
          max-total: 200
          max-per-route: 100
          ttl: 300000ms
          validate-after-inactivity: 2000ms
          evict-idle-connections: 30000ms

app:
  base-url: https://analysis-dispatcher.onrender.com

telegram:
  bot:
    token: ${bot_token}
    username: ${bot_username}
    webhook-path: /telegram/webhook

public-url:
  xau-price: https://api.gold-api.com/price/XAU
  forex-factory: https://nfs.faireconomy.media/ff_calendar_thisweek.json