name: Query Gold Price

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test automatic trigger
        run: |
          echo "Workflow triggered!"
          date -u